### ISSUE TITLE
Find out what the survey questions are.

### ISSUE THREAD

**Issue by PaulVBell** [prestevez/rds-course-2023-session-1-group-2#7]

**Comment by aaastand** [comment]
The user guide in the documentation  [here ](https://doc.ukdataservice.ac.uk/doc/7724/mrdoc/pdf/7724_eqls_2007-2011_user_guide_v2.pdf)explains what the survey questions are. See the tables.

**Comment by aaa-alsayed** [comment]
[Here ](https://www.eurofound.europa.eu/sites/default/files/ef_files/docs/areas/qualityoflife/translated_versions_eqls2007/unitedkingdom.pdf)is a link to the 2007 survey. Other languages are found [here](https://www.eurofound.europa.eu/surveys/european-quality-of-life-surveys/european-quality-of-life-survey-2007/eqls-2007-questionnaire-translation).
